Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network :forwarded_port, guest: 3000 , host: 3000
    config.vm.provision "docker" do |d|
            d.pull_images "aldry1303/despesa:1.0.2"
            config.vm.provision "shell", inline: "docker run -p 3000:3000 -d aldry1303/despesa"
    end
  end